<?php



return [
    'namespaces' => [
        'FastRoute'=>dirname(__DIR__).DS.'Library'.DS.'nikic'.DS.'FastRoute'.DS.'src',
        'Psr\Log'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'log'.DS.'Psr'.DS.'Log',
        'Fig\Http\Message'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'http-message-util'.DS.'src',
        'Psr\Http\Message'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'http-message'.DS.'src',
        'Fig\Link'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'link-util'.DS.'src',
        'Psr\Container'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'container'.DS.'src',
        'Fig\Cache'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'cache-util'.DS.'src',
        'Psr\Link'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'link'.DS.'src',
        'Psr\Cache'=>dirname(__DIR__).DS.'Library'.DS.'php-fig'.DS.'cache'.DS.'src',
        'Monolog'=>dirname(__DIR__).DS.'Library'.DS.'Seldaek'.DS.'monolog'.DS.'src'.DS.'Monolog',
        'Noodlehaus'=>dirname(__DIR__).DS.'Library'.DS.'hassankhan'.DS.'config'.DS.'src',
        'MongoDB'=>dirname(__DIR__).DS.'Library'.DS.'mongodb'.DS.'mongo-php-library'.DS.'src',
        'Curl'=>dirname(__DIR__).DS.'Library'.DS.'php-curl-class'.DS.'php-curl-class'.DS.'src'.DS.'Curl',
        'GuzzleHttp\Ring'=>dirname(__DIR__).DS.'Library'.DS.'guzzle'.DS.'RingPHP'.DS.'src',
        'GuzzleHttp\Stream'=>dirname(__DIR__).DS.'Library'.DS.'guzzle'.DS.'streams'.DS.'src',
        'React\Promise'=>dirname(__DIR__).DS.'Library'.DS.'reactphp'.DS.'promise'.DS.'src',
        'Elasticsearch'=>dirname(__DIR__).DS.'Library'.DS.'elastic'.DS.'elasticsearch-php'.DS.'src'.DS.'Elasticsearch',
        'Symfony\Component\Intl'=>dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'intl',
        'Symfony\Polyfill'=>dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src',
        'PhpAmqpLib'=>dirname(__DIR__).DS.'Library'.DS.'php-amqplib'.DS.'php-amqplib'.DS.'PhpAmqpLib',
        'Ds'=>dirname(__DIR__).DS.'Library'.DS.'php-ds'.DS.'polyfill'.DS.'src','.DS.'/need ext-ds
        'League\Plates'=>dirname(__DIR__).DS.'Library'.DS.'thephpleague'.DS.'plates'.DS.'src',
        'voku\helper' => dirname(__DIR__).DS.'Library'.DS.'voku'.DS.'anti-xss'.DS.'src'.DS.'voku'.DS.'helper',
        'voku' => dirname(__DIR__).DS.'Library'.DS.'voku'.DS.'portable-utf8'.DS.'src'.DS.'voku',
        'Kernel'=>dirname(__DIR__),
    ],
    'files' => [
        dirname(__DIR__).DS.'Library'.DS.'nikic'.DS.'FastRoute'.DS.'src'.DS.'functions.php',
        dirname(__DIR__).DS.'Library'.DS.'mongodb'.DS.'mongo-php-library'.DS.'src'.DS.'functions.php',
        dirname(__DIR__).DS.'Library'.DS.'reactphp'.DS.'promise'.DS.'src'.DS.'functions_include.php',
        dirname(__DIR__).DS.'Helpers'.DS.'Common.php',
        dirname(__DIR__).DS.'Library'.DS.'ircmaxell'.DS.'password_compat'.DS.'lib'.DS.'password.php',
        dirname(__DIR__).DS.'Library'.DS.'paragonie'.DS.'random_compat'.DS.'lib'.DS.'random.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'intl'.DS.'Resources'.DS.'stubs'.DS.'Collator.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'intl'.DS.'Resources'.DS.'stubs'.DS.'IntlDateFormatter.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'intl'.DS.'Resources'.DS.'stubs'.DS.'Locale.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'intl'.DS.'Resources'.DS.'stubs'.DS.'NumberFormatter.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Apcu'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Php70'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Iconv'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Intl'.DS.'Grapheme'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Intl'.DS.'Icu'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Intl'.DS.'Normalizer'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Mbstring'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Xml'.DS.'bootstrap.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.DS.'Intl'.DS.'Normalizer'.DS.'Resources'.DS.'stubs'.DS.'Normalizer.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'ArithmeticError.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'AssertionError.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'DivisionByZeroError.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'Error.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'ParseError.php',
        dirname(__DIR__).DS.'Library'.DS.'symfony'.DS.'polyfill'.DS.'src'.'Php70'.DS.'Resources'.DS.'stubs'.DS.'TypeError.php',
        dirname(__DIR__).DS.'Library'.DS.'voku'.DS.'portable-utf8'.DS.'bootstrap.php',

    ],
    ];
